name: ebill
description: "Invoice generating desktop app built with Flutter"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 4.3.0
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.11.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.6
  path: ^1.8.3
  path_provider: ^2.0.15
  file_picker: ^10.2.0
  permission_handler: ^12.0.1
  share_plus: ^11.0.0
  crypto: ^3.0.3
  uuid: ^4.0.0
  csv: ^6.0.0
  archive: ^4.0.0
  flutter_riverpod: ^2.5.1
  open_file: ^3.3.2
  url_launcher: ^6.2.6
  http: ^1.2.0
  fl_chart: ^0.69.0
  downloads_path_provider_28: any
  syncfusion_flutter_pdfviewer: ^30.1.40
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  window_manager: ^0.5.1
  screen_retriever: ^0.2.0
  flutter_svg: ^2.0.10+1
  image: ^4.2.0
  qr: ^3.0.1
  flex_color_picker: ^3.6.0
  thermal_printer: ^1.0.5
  flutter_esc_pos_utils: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  package_rename: ^1.10.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
   - assets/images/celltek_logo.png
   - assets/templates/classic.png
   - assets/templates/modern.png
   - assets/templates/minimal.png
   - assets/fonts/DejaVuSans.ttf
   - assets/fonts/DejaVuSans-Bold.ttf
   - assets/fonts/DejaVuSans-Oblique.ttf
   - assets/fonts/DejaVuSans-BoldOblique.ttf
   - assets/fonts/lklug.ttf
   - assets/fonts/NotoSansDevanagari-Bold.ttf
   - assets/fonts/NotoSansDevanagari-Regular.ttf
   - assets/fonts/NotoSansMalayalam-Bold.ttf
   - assets/fonts/NotoSansMalayalam-Regular.ttf
   - assets/fonts/NotoSansTamil-Regular.ttf
   - assets/fonts/NotoSansTamil-Bold.ttf
   - assets/fonts/NotoSansKannada-Regular.ttf
   - assets/fonts/NotoSansKannada-Bold.ttf
   - assets/fonts/NotoSansTelugu-Regular.ttf
   - assets/fonts/NotoSansTelugu-Bold.ttf

flutter_launcher_icons:
  image_path: "assets/images/celltek_logo.png"
  windows:
    generate: true
    icon_size: 256
  macos:
    generate: true
  web:
    generate: true
    background_color: "#FFFFFF"
    theme_color: "#002E78"

package_rename_config:
  linux:
    app_name: Ebill
    package_name: ebill
    exe_name: ebill

  windows:
    app_name: Ebill
    organization: jagadih_V.J
    copyright_notice: Copyright ©️ 2025 jagadih_V.J. All rights reserved.
    exe_name: ebill

  web:
    app_name: Ebill
    short_app_name: Ebill
    description: Invoice generating desktop app built with Flutter
