enum InvoiceTemplate {
  classic,
  modern,
  minimal,
  executive,
  compact, // A6-optimized compact/receipt template
  thermal, // 80mm/58mm thermal receipt template
}

enum BackupType { database, json }

enum SettingKey {
  logoPosition,
  invoicePrefix,
  additionalInfo,
  thankYouNote,
  currency,
  upiId, // kept for backward-compat read only
  showUpiQr,
  upiIds, // JSON list of UpiEntry objects
  showGstFields, // whether to show GST/GSTIN fields
  fractionalQuantity, // whether to allow decimal quantities (e.g. 1.5 hrs)
  quantityLabel, // default label for the Qty column (e.g. "Words", "Hours")
  logoSize, // logo size on PDF: 'small' | 'medium' | 'large'
  businessType, // 'product' | 'service' | 'both'
  showQuantity, // whether to show quantity field (default true)
  bankAccounts, // JSON list of BankAccount objects
  showBankDetails, // whether to show bank details on PDF
  showDiscount, // whether to show discount column on PDF (default true)
  showTypeTag, // whether to show product/service tag on invoice items (default true)
  lastUpdateCheck, // ISO timestamp of last GitHub release API call
  lastKnownLatestVersion, // latest version tag returned by last API call
  lastNotifiedVersion, // version for which the update dialog was last shown
  dateFormat, // date display pattern: 'dd/MM/yyyy' | 'MM/dd/yyyy' | 'dd MMM yyyy' | 'yyyy-MM-dd'
  showInvoiceFooterBranding, // show "Generated by Ebill" in invoice PDF footer
  pdfThemeColor, // custom PDF accent/theme color as #RRGGBB
  dashboardLayout, // which dashboard layout to use: 'default' | 'classic' | 'simple'
  layoutBannerDismissed, // '1' once user dismisses the new-layouts discovery banner
  signatureImage, // base64-encoded signature image
  signaturePosition, // 'left' | 'right'
  showPreviousBalance, // whether to show calculated Previous Balance Due on PDFs
  pageSize, // 'a4' | 'a6'
  showTotalQuantity, // show total quantity row in compact template footer
  supportBannerDismissed, // milestone at which support banner was last dismissed: '10' | '50' | '100'
  invoiceStartingNumber, // starting invoice number (only editable when invoice count is zero)
  defaultTaxRate, // default invoice tax rate percentage (e.g. '18')
  thermalWidthMargin, // chars trimmed off the thermal printer's textbook width to avoid edge clipping on real hardware; default '1'
  thermalItemLayout, // 'table' | 'detailed' — how items print on thermal receipts; default 'table'
  invoiceTemplate, // used by cloud edition's generic setSetting/getSetting path
  companyLogo, // used by cloud edition's generic setSetting/getSetting path
}

extension SettingKeyExtension on SettingKey {
  String get key {
    switch (this) {
      case SettingKey.logoPosition:
        return 'logo_position';
      case SettingKey.invoicePrefix:
        return 'invoice_prefix';
      case SettingKey.additionalInfo:
        return 'additional_info';
      case SettingKey.thankYouNote:
        return 'thank_you_note';
      case SettingKey.currency:
        return 'currency';
      case SettingKey.upiId:
        return 'upi_id';
      case SettingKey.showUpiQr:
        return 'show_upi_qr';
      case SettingKey.upiIds:
        return 'upi_ids';
      case SettingKey.showGstFields:
        return 'show_gst_fields';
      case SettingKey.fractionalQuantity:
        return 'fractional_quantity';
      case SettingKey.quantityLabel:
        return 'quantity_label';
      case SettingKey.logoSize:
        return 'logo_size';
      case SettingKey.businessType:
        return 'business_type';
      case SettingKey.showQuantity:
        return 'show_quantity';
      case SettingKey.bankAccounts:
        return 'bank_accounts';
      case SettingKey.showBankDetails:
        return 'show_bank_details';
      case SettingKey.showDiscount:
        return 'show_discount';
      case SettingKey.showTypeTag:
        return 'show_type_tag';
      case SettingKey.lastUpdateCheck:
        return 'last_update_check';
      case SettingKey.lastKnownLatestVersion:
        return 'last_known_latest_version';
      case SettingKey.lastNotifiedVersion:
        return 'last_notified_version';
      case SettingKey.dateFormat:
        return 'date_format';
      case SettingKey.showInvoiceFooterBranding:
        return 'show_invoice_footer_branding';
      case SettingKey.pdfThemeColor:
        return 'pdf_theme_color';
      case SettingKey.dashboardLayout:
        return 'dashboard_layout';
      case SettingKey.layoutBannerDismissed:
        return 'layout_banner_dismissed';
      case SettingKey.signatureImage:
        return 'signature_image';
      case SettingKey.signaturePosition:
        return 'signature_position';
      case SettingKey.showPreviousBalance:
        return 'show_previous_balance';
      case SettingKey.pageSize:
        return 'page_size';
      case SettingKey.showTotalQuantity:
        return 'show_total_quantity';
      case SettingKey.supportBannerDismissed:
        return 'support_banner_dismissed';
      case SettingKey.invoiceStartingNumber:
        return 'invoice_starting_number';
      case SettingKey.defaultTaxRate:
        return 'default_tax_rate';
      case SettingKey.thermalWidthMargin:
        return 'thermal_width_margin';
      case SettingKey.thermalItemLayout:
        return 'thermal_item_layout';
      case SettingKey.invoiceTemplate:
        return 'invoice_template';
      case SettingKey.companyLogo:
        return 'company_logo';
    }
  }
}

enum PageSize { a4, a6, thermal80, thermal58 }

extension InvoiceTemplatePageSizeExtension on InvoiceTemplate {
  bool supportsPageSize(PageSize pageSize) {
    if (pageSize == PageSize.a6) {
      return this == InvoiceTemplate.compact;
    }
    if (pageSize == PageSize.thermal80 || pageSize == PageSize.thermal58) {
      return this == InvoiceTemplate.thermal;
    }
    return this != InvoiceTemplate.compact && this != InvoiceTemplate.thermal;
  }
}

InvoiceTemplate defaultInvoiceTemplateForPageSize(PageSize pageSize) {
  switch (pageSize) {
    case PageSize.a6:
      return InvoiceTemplate.compact;
    case PageSize.thermal80:
    case PageSize.thermal58:
      return InvoiceTemplate.thermal;
    default:
      return InvoiceTemplate.classic;
  }
}

InvoiceTemplate effectiveInvoiceTemplateForPageSize(
  InvoiceTemplate template,
  PageSize pageSize,
) {
  return template.supportsPageSize(pageSize)
      ? template
      : defaultInvoiceTemplateForPageSize(pageSize);
}

extension PageSizeExtension on PageSize {
  String get key {
    switch (this) {
      case PageSize.a4:
        return 'a4';
      case PageSize.a6:
        return 'a6';
      case PageSize.thermal80:
        return 'thermal80';
      case PageSize.thermal58:
        return 'thermal58';
    }
  }

  String get label {
    switch (this) {
      case PageSize.a4:
        return 'Standard A4';
      case PageSize.a6:
        return 'Standard A6';
      case PageSize.thermal80:
        return 'Thermal Paper 80mm';
      case PageSize.thermal58:
        return 'Thermal Paper 58mm';
    }
  }

  static PageSize fromKey(String? key) {
    switch (key) {
      case 'a6':
        return PageSize.a6;
      case 'thermal80':
        return PageSize.thermal80;
      case 'thermal58':
        return PageSize.thermal58;
      default:
        return PageSize.a4;
    }
  }
}

class CompactPdfTotalsStyle {
  const CompactPdfTotalsStyle({
    this.width = 128,
    this.rowFontSize = 5.5,
    this.highlightFontSize = 6.0,
    this.rowHorizontalPadding = 4,
    this.rowVerticalPadding = 2,
    this.highlightHorizontalPadding = 4,
    this.highlightVerticalPadding = 3,
    this.borderRadius = 4,
  });

  final double width;
  final double rowFontSize;
  final double highlightFontSize;
  final double rowHorizontalPadding;
  final double rowVerticalPadding;
  final double highlightHorizontalPadding;
  final double highlightVerticalPadding;
  final double borderRadius;
}

const compactPdfTotalsStyle = CompactPdfTotalsStyle();

class CompactPdfLayoutStyle {
  const CompactPdfLayoutStyle({
    this.logoScale = 0.6,
    this.tableFontSize = 6.4,
    this.tableHorizontalPadding = 4,
    this.tableVerticalPadding = 2.2,
    this.headerGap = 5,
    this.headerPadding = 4,
    this.signatureTopGap = 5,
    this.signatureImageHeight = 24,
    this.signatureLabelGap = 1.5,
    this.signatureLabelFontSize = 5.8,
    this.footerBrandingFontSize = 5.6,
    this.footerTopMargin = 4,
  });

  final double logoScale;
  final double tableFontSize;
  final double tableHorizontalPadding;
  final double tableVerticalPadding;
  final double headerGap;
  final double headerPadding;
  final double signatureTopGap;
  final double signatureImageHeight;
  final double signatureLabelGap;
  final double signatureLabelFontSize;
  final double footerBrandingFontSize;
  final double footerTopMargin;
}

const compactPdfLayoutStyle = CompactPdfLayoutStyle();

enum DateFormatOption {
  ddmmyyyy, // dd/MM/yyyy  — default
  mmddyyyy, // MM/dd/yyyy  — US
  ddMmmyyyy, // dd MMM yyyy — unambiguous
  yyyymmdd, // yyyy-MM-dd  — ISO
}

extension DateFormatOptionExtension on DateFormatOption {
  String get key {
    switch (this) {
      case DateFormatOption.ddmmyyyy:
        return 'dd/MM/yyyy';
      case DateFormatOption.mmddyyyy:
        return 'MM/dd/yyyy';
      case DateFormatOption.ddMmmyyyy:
        return 'dd MMM yyyy';
      case DateFormatOption.yyyymmdd:
        return 'yyyy-MM-dd';
    }
  }

  String get label {
    switch (this) {
      case DateFormatOption.ddmmyyyy:
        return 'DD/MM/YYYY  (e.g. 15/04/2026)';
      case DateFormatOption.mmddyyyy:
        return 'MM/DD/YYYY  (e.g. 04/15/2026)';
      case DateFormatOption.ddMmmyyyy:
        return 'DD MMM YYYY  (e.g. 15 Apr 2026)';
      case DateFormatOption.yyyymmdd:
        return 'YYYY-MM-DD  (e.g. 2026-04-15)';
    }
  }

  static DateFormatOption fromKey(String? key) {
    switch (key) {
      case 'MM/dd/yyyy':
        return DateFormatOption.mmddyyyy;
      case 'dd MMM yyyy':
        return DateFormatOption.ddMmmyyyy;
      case 'yyyy-MM-dd':
        return DateFormatOption.yyyymmdd;
      default:
        return DateFormatOption.ddmmyyyy;
    }
  }
}

enum BusinessType {
  product,
  service,
  both,
}

extension BusinessTypeExtension on BusinessType {
  String get key {
    switch (this) {
      case BusinessType.product:
        return 'product';
      case BusinessType.service:
        return 'service';
      case BusinessType.both:
        return 'both';
    }
  }

  String get label {
    switch (this) {
      case BusinessType.product:
        return 'Product-based';
      case BusinessType.service:
        return 'Service-based';
      case BusinessType.both:
        return 'Both';
    }
  }

  static BusinessType fromKey(String? key) {
    switch (key) {
      case 'product':
        return BusinessType.product;
      case 'service':
        return BusinessType.service;
      default:
        return BusinessType.both;
    }
  }
}

/// A single UPI payment account entry.
class UpiEntry {
  final String label; // friendly name, e.g. "HDFC Bank" (may be empty)
  final String id; // UPI ID, e.g. "business@okhdfcbank"
  final bool isDefault; // whether this is the default account

  const UpiEntry(
      {required this.label, required this.id, this.isDefault = false});

  Map<String, dynamic> toJson() =>
      {'label': label, 'id': id, 'isDefault': isDefault};

  factory UpiEntry.fromJson(Map<String, dynamic> json) => UpiEntry(
        label: json['label'] as String? ?? '',
        id: json['id'] as String? ?? '',
        isDefault: json['isDefault'] as bool? ?? false,
      );

  /// Returns the label if set, otherwise falls back to the UPI ID itself.
  String get displayLabel => label.trim().isNotEmpty ? label.trim() : id;
}

/// A single bank account entry.
class BankAccount {
  final String label; // friendly name, e.g. "Business Account"
  final String bankName; // e.g. "HDFC Bank"
  final String accountNumber; // e.g. "123456789012"
  final String ifscCode; // e.g. "HDFC0001234"
  final bool isDefault;

  const BankAccount({
    required this.label,
    required this.bankName,
    required this.accountNumber,
    required this.ifscCode,
    this.isDefault = false,
  });

  Map<String, dynamic> toJson() => {
        'label': label,
        'bankName': bankName,
        'accountNumber': accountNumber,
        'ifscCode': ifscCode,
        'isDefault': isDefault,
      };

  factory BankAccount.fromJson(Map<String, dynamic> json) => BankAccount(
        label: json['label'] as String? ?? '',
        bankName: json['bankName'] as String? ?? '',
        accountNumber: json['accountNumber'] as String? ?? '',
        ifscCode: json['ifscCode'] as String? ?? '',
        isDefault: json['isDefault'] as bool? ?? false,
      );

  String get displayLabel =>
      label.trim().isNotEmpty ? label.trim() : bankName.trim();
}

class CurrencyOption {
  final String code;
  final String symbol;
  final String name;

  const CurrencyOption({
    required this.code,
    required this.symbol,
    required this.name,
  });
}

class SupportedCurrencies {
  static const List<CurrencyOption> all = [
    // default currency
    CurrencyOption(code: 'INR', symbol: 'Rs.', name: 'Indian Rupee'),
    // sorted
    CurrencyOption(code: 'AED', symbol: 'AED.', name: 'UAE Dirham'),
    CurrencyOption(code: 'AUD', symbol: 'A\$', name: 'Australian Dollar'),
    CurrencyOption(code: 'CAD', symbol: 'C\$', name: 'Canadian Dollar'),
    CurrencyOption(code: 'EUR', symbol: '€', name: 'Euro'),
    CurrencyOption(code: 'GBP', symbol: '£', name: 'British Pound'),
    CurrencyOption(code: 'JMD', symbol: 'J\$', name: 'Jamaican Dollar'),
    CurrencyOption(code: 'JPY', symbol: '¥', name: 'Japanese Yen'),
    CurrencyOption(code: 'KES', symbol: 'KSh.', name: 'Kenyan Shilling'),
    CurrencyOption(code: 'LKR', symbol: 'රු', name: 'Sri Lankan Rupee'),
    CurrencyOption(code: 'MWK', symbol: 'MK', name: 'Malawian Kwacha'),
    CurrencyOption(code: 'MYR', symbol: 'RM.', name: 'Malaysian Ringgit'),
    CurrencyOption(code: 'NGN', symbol: '₦', name: 'Nigerian Naira'),
    CurrencyOption(code: 'NPR', symbol: 'Rs.', name: 'Nepalese Rupee'),
    CurrencyOption(code: 'NZD', symbol: 'NZ\$', name: 'New Zealand Dollar'),
    CurrencyOption(code: 'OMR', symbol: 'OMR.', name: 'Omani Rial'),
    CurrencyOption(code: 'PKR', symbol: 'Rs.', name: 'Pakistani Rupee'),
    CurrencyOption(code: 'QAR', symbol: 'QAR.', name: 'Qatari Riyal'),
    CurrencyOption(code: 'SAR', symbol: 'SAR.', name: 'Saudi Riyal'),
    CurrencyOption(code: 'SGD', symbol: 'S\$', name: 'Singapore Dollar'),
    CurrencyOption(code: 'USD', symbol: '\$', name: 'US Dollar'),
    CurrencyOption(code: 'ZAR', symbol: 'R.', name: 'South African Rand'),
  ];

  static CurrencyOption fromCode(String code) {
    return all.firstWhere(
      (c) => c.code == code,
      orElse: () => all.first,
    );
  }
}

enum TaxMode {
  none,
  global,
  perItem,
}

extension TaxModeExtension on TaxMode {
  String get key {
    switch (this) {
      case TaxMode.none:
        return 'none';
      case TaxMode.global:
        return 'global';
      case TaxMode.perItem:
        return 'per_item';
    }
  }

  static TaxMode fromKey(String? key) {
    switch (key) {
      case 'none':
        return TaxMode.none;
      case 'per_item':
        return TaxMode.perItem;
      default:
        return TaxMode.global;
    }
  }
}

enum LogoPosition { left, right }

/// Returns the label used for a company's tax registration number on PDFs.
/// Falls back to 'GSTIN' for India and for unset countries (backward compat).
String taxLabel(String? country) {
  if (country == null || country.isEmpty || country == 'India') return 'GSTIN';
  return 'Tax/VAT No';
}

/// Returns the label for a personal tax ID field.
/// India → 'PAN', everyone else → 'TIN'.
String panLabel(String? country) {
  if (country == null || country.isEmpty || country == 'India') return 'PAN';
  return 'TIN';
}

/// Full list of world countries (alphabetical).
class AppCountries {
  static const List<String> all = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo (Brazzaville)',
    'Congo (Kinshasa)',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czech Republic',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
  ];
}

enum PaymentStatus {
  unpaid,
  partial,
  paid,
}

extension LogoPositionExtension on LogoPosition {
  String get key {
    switch (this) {
      case LogoPosition.left:
        return 'left';
      case LogoPosition.right:
        return 'right';
    }
  }
}
